### ISSUE TITLE
Invalid XSD generation

### ISSUE THREAD

**Issue by hidde-jan** [hrennau/shax#2]
I've been playing around with SHAX today to generate both SHACL shapes and XSD schemas, but the XSD that is generated is invalid. The `name` attribute cannot contain `:`, but also `rdfs:label` does not really exists in 'XSD'-land. This could also be a modelling issue, but so, how should one model the `(rdfs:)label` property such that it is an `rdfs:label` in RDF-land.

## Files

SHAX:

```xml
<shax:model defaultCard="1" xmlns:shax="http://shax.org/ns/model" xmlns:ex="http://example.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:rdfs="https://www.w3.org/2000/01/rdf-schema">
    <shax:property name="ex:Student" type="ex:StudentType"/>

    <shax:objectType name="ex:StudentType" class="ex:Student">
        <rdfs:label />
        <ex:plays card="+" type="ex:SportType"/>
    </shax:objectType>

    <shax:objectType name="ex:SportType" class="ex:Sport">
        <rdfs:label />
    </shax:objectType>
</shax:model>
```

generated SHACL:

```turtle
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix shax: <http://shax.org/ns/model#> .
@prefix nons: <http://shax.org/ns/nonamespace#> .
@prefix e_: <http://shax.org/ns/model/element-equivalent#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace#> .
@prefix xs:  <http://www.w3.org/2001/XMLSchema#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

@prefix ex: <http://example.com/> .
@prefix rdfs: <https://www.w3.org/2000/01/rdf-schema#> .

#
#top-level elements
#==================
#
e_:_RootResource___ex___Student
    a sh:NodeShape ;
    sh:targetObjectsOf ex:Student ;
    sh:node ex:StudentType .

ex:StudentType
   a sh:NodeShape;
   sh:targetClass ex:Student;
   sh:class ex:Student;
   sh:property [
      sh:path rdfs:label;
      sh:minCount 1;
      sh:maxCount 1;
   ];
   sh:property [
      sh:path ex:plays;
      sh:minCount 1;
      sh:node ex:SportType;
   ].
ex:SportType
   a sh:NodeShape;
   sh:targetClass ex:Sport;
   sh:class ex:Sport;
   sh:property [
      sh:path rdfs:label;
      sh:minCount 1;
      sh:maxCount 1;
   ].
```

generated XSD:

```xml
<xs:schema xmlns:shax="http://shax.org/ns/model" xmlns:a="http://example.com/" xmlns:b="https://www.w3.org/2000/01/rdf-schema" xmlns:zz="http://www.ttools.org/structure" xmlns:shax_1="http://www.shax.org/ns/model" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://example.com/" elementFormDefault="qualified">
  <xs:element name="Student" type="a:StudentType"/>
  <xs:complexType name="StudentType">
    <xs:sequence>
      <xs:element name="b:label"/>
      <xs:element name="plays" maxOccurs="unbounded" type="a:SportType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SportType">
    <xs:sequence>
      <xs:element name="b:label"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
```

**Comment by hrennau** [comment]
HJ, this sounds like a bug - thank you for reporting it!
Tonight, I'll investigate.
Cheers,HJ


    Am Dienstag, 7. Mai 2019, 15:31:08 MESZ hat Hidde-Jan Jongsma <notifications@github.com> Folgendes geschrieben:  
 
 
I've been playing around with SHAX today to generate both SHACL shapes and XSD schemas, but the XSD that is generated is invalid. The name attribute cannot contain :, but also rdfs:label does not really exists in 'XSD'-land. This could also be a modelling issue, but so, how should one model the (rdfs:)label property such that it is an rdfs:label in RDF-land.

Files

SHAX:
<shax:model defaultCard="1" xmlns:shax="http://shax.org/ns/model" xmlns:ex="http://example.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:rdfs="https://www.w3.org/2000/01/rdf-schema">
    <shax:property name="ex:Student" type="ex:StudentType"/>

    <shax:objectType name="ex:StudentType" class="ex:Student">
        <rdfs:label />
        <ex:plays card="+" type="ex:SportType"/>
    </shax:objectType>

    <shax:objectType name="ex:SportType" class="ex:Sport">
        <rdfs:label />
    </shax:objectType>
</shax:model>
generated SHACL:
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix shax: <http://shax.org/ns/model#> .
@prefix nons: <http://shax.org/ns/nonamespace#> .
@prefix e_: <http://shax.org/ns/model/element-equivalent#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace#> .
@prefix xs:  <http://www.w3.org/2001/XMLSchema#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

@prefix ex: <http://example.com/> .
@prefix rdfs: <https://www.w3.org/2000/01/rdf-schema#> .

#
#top-level elements
#==================
#
e_:_RootResource___ex___Student
    a sh:NodeShape ;
    sh:targetObjectsOf ex:Student ;
    sh:node ex:StudentType .

ex:StudentType
   a sh:NodeShape;
   sh:targetClass ex:Student;
   sh:class ex:Student;
   sh:property [
      sh:path rdfs:label;
      sh:minCount 1;
      sh:maxCount 1;
   ];
   sh:property [
      sh:path ex:plays;
      sh:minCount 1;
      sh:node ex:SportType;
   ].
ex:SportType
   a sh:NodeShape;
   sh:targetClass ex:Sport;
   sh:class ex:Sport;
   sh:property [
      sh:path rdfs:label;
      sh:minCount 1;
      sh:maxCount 1;
   ].
generated XSD:
<xs:schema xmlns:shax="http://shax.org/ns/model" xmlns:a="http://example.com/" xmlns:b="https://www.w3.org/2000/01/rdf-schema" xmlns:zz="http://www.ttools.org/structure" xmlns:shax_1="http://www.shax.org/ns/model" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://example.com/" elementFormDefault="qualified">
  <xs:element name="Student" type="a:StudentType"/>
  <xs:complexType name="StudentType">
    <xs:sequence>
      <xs:element name="b:label"/>
      <xs:element name="plays" maxOccurs="unbounded" type="a:SportType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SportType">
    <xs:sequence>
      <xs:element name="b:label"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

**Comment by hrennau** [comment]
Fixed. Local properties with a name from a namespace which is different from the namespace of the name of the containing complex type are now mapped to xs:element/@ref, which references a global element declaration in that namespace. Note that in this case you have at least two XSDs (one for each target namespace), and therefore you must pass a further parameter, $odir, which is the output directory. Default schema names are schema1.xsd, schema2.xsd, ... You can control the schema names using parameters $ofile and/or $osuffixes. $ofile is a name base to which suffixes are added. Default value is "schema". Default suffixes are "1", "2", ... You can specify a different name base ($ofile) and/or different suffixes (e.g. osuffixes=-main -util). Note that the suffixes are automatically extended by a trailing ".xsd". Example call:

shax "xsd?shax=shax/studentType.shax.xml, odir=xsds, osuffixes=-main -util, ofile=student"

**Comment by hrennau** [comment]
One remark about the suitability of rdfs:label in XML data and XSD.

Currently there is no support for using different names in the generated SHAX and XSD schemas. I am aware of the fact that more often than not one may wish to use different names in the XSDs, and also different structures, e.g. adding or removing levels. This is a big topic which cannot be addressed on the fly. Ultimately, probably, the SHAX vocabulary will be extended to allow the specification of different names to be used in a generated XSD, as well as structural modifications. These things should mature before starting to implement them.

**Comment by hrennau** [comment]
student-main.xsd
```
<xs:schema xmlns:shax_1="http://www.shax.org/ns/model" 
   xmlns:zz="http://www.ttools.org/structure"
   xmlns:b="http://www.w3.org/2000/01/rdf-schema" 
   xmlns:a="http://example.com/"
   xmlns:shax="http://shax.org/ns/model" xmlns:xs="http://www.w3.org/2001/XMLSchema"
      targetNamespace="http://example.com/" elementFormDefault="qualified">
  <xs:import namespace="http://www.w3.org/2000/01/rdf-schema"
    schemaLocation="C:/projects/shax/shacl/work/xsds/student-util.xsd"/>
  <xs:element name="Student" type="a:StudentType"/>
  <xs:complexType name="StudentType">
    <xs:sequence>
      <xs:element ref="b:label"/>
      <xs:element name="plays" maxOccurs="unbounded" type="a:SportType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SportType">
    <xs:sequence>
      <xs:element ref="b:label"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
```
student-util.xsd
```
<xs:schema xmlns:shax_1="http://www.shax.org/ns/model" 
   xmlns:zz="http://www.ttools.org/structure" 
   xmlns:b="http://www.w3.org/2000/01/rdf-schema" 
   xmlns:a="http://example.com/" 
   xmlns:shax="http://shax.org/ns/model" 
   xmlns:xs="http://www.w3.org/2001/XMLSchema" 
   targetNamespace="http://www.w3.org/2000/01/rdf-schema" 
   elementFormDefault="qualified">
  <xs:element name="label" type="xs:string"/>
</xs:schema>
```
